KTOR-3420 Implement multiplatform CLI generator of Ktor projects
ktorio/ktor-cli pull request #1
Opened 2021-12-09 15:50 UTC by Ololoshechkin

First version of the CLI generator.
For now it only supports windows64, mac64, linux64 and only provides 2 functions:
- `ktor generate <name>`
-`ktor run <name>`

As well as debug version with a custom host:
- `ktor <host> generate <name>`
-`ktor <host> run <name>`

In future some parts may be fixed/changed. Other than that more options will be added.

Note: currently on Windows the only working option that can be run from any shell is the attached script. I've checked that it works under win10 but it still requires some checks under other windows builds. Also this solution may be rewritten to some other tool in the future.

2021-12-09 16:05 UTC, e5l requested changes

2021-12-09 16:05 UTC, e5l commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please add .idea to ignore

2021-12-09 16:05 UTC, e5l commented on build.gradle.kts
> +//                implementation("io.ktor:ktor-client-content-negotiation:1.6.5")
comments should be removed

2021-12-09 16:05 UTC, e5l commented on src/mingwX64Main/c_interop/WinApi.def
> +compilerOpts.linux = -I/usr/include -I/usr/include/x86_64-linux-gnu
`curl` requires runtime dependency right now, the final binary will not work without additional `dynamic library`

2021-12-09 16:05 UTC, e5l commented on src/mingwX64Main/kotlin/io/ktor/generator/cli/CliGenerator.kt
> +        "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip"
consider using latest `LTS` jdk version

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/io/ktor/generator/cli/installer/KtorInstaller.kt
> +    private fun hasAdHockJdk(): Boolean = findCustomJdk() != null
Consider renaming this method

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/io/ktor/generator/cli/installer/KtorInstaller.kt
> +        println("JDK 11 not found.\nJdk download path:$jdkDownloadUrl\nDownloading JDK-11 from server, please wait...")
We should extract such string constants in a separate file and consider localization in the future.

It's hard to proofread it right now

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/io/ktor/generator/cli/installer/KtorInstaller.kt
> +    protected companion object {
can be public

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/io/ktor/generator/cli/installer/UnixKtorInstaller.kt
> +    bitness: String,
architecture

2021-12-09 16:05 UTC, e5l commented on src/mingwX64Main/kotlin/io/ktor/generator/cli/CliGenerator.kt
> +class WindowsKtorInstaller(client: HttpClient, ktorBackendHost: String) : KtorInstaller(client, ktorBackendHost) {
I'm not sure about inheritance here, it's not really needed
I would make it as class instances and all logic move to `expect/actual`.

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/CliGeneratorMain.kt
> +    val command = args.getOrNull(argIndex++) ?: reportError(COMMAND_MISSING)
We should consider using CLI parsing library instead

2021-12-09 16:05 UTC, e5l commented on src/nativeMain/kotlin/io/ktor/generator/cli/installer/KtorInstaller.kt
> +internal fun getEnv(name: String): String? = getenv(name)?.toKString()
Consider extracting utility functions to the separate file

2021-12-09 18:43 UTC, Ololoshechkin commented on src/mingwX64Main/c_interop/WinApi.def
> +compilerOpts.linux = -I/usr/include -I/usr/include/x86_64-linux-gnu
Sorry, forgot to add it in gradle for windows

2021-12-10 21:44 UTC, Ololoshechkin commented on src/mingwX64Main/kotlin/io/ktor/generator/cli/CliGenerator.kt
> +        "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip"
Why is it important?

2021-12-10 22:04 UTC, Stexxe commented
Tests for the core functionality are missing.

2021-12-16 15:07 UTC, e5l approved these changes
Please add a couple of integration tests before merging

2021-12-17 21:36 UTC, merged